apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-shopify-loader
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-shopify-loader
  template:
    metadata:
      labels:
        app: ingestion-shopify-loader
    spec:
      containers:
        - name: loader
          image: minkowski/ingestion-shopify:latest
          envFrom:
            - secretRef:
                name: shopify-loader-secrets
          ports:
            - containerPort: 8080
